web:
  build: .
  working_dir: /data
  command: python app.py
  links:
    - db
  volumes:
    - .:/data
  ports:
    - "5050:5050"

db:
  image: mysql
  environment:
      MYSQL_ROOT_PASSWORD: NpmFmMxjmSXk46k
  ports:
    - "3306:3306"